### ISSUE TITLE
Session is not saved when computer is shut down

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [DeaDBeeF-Player/deadbeef#1014]
Original [issue 1112](https://code.google.com/p/ddb/issues/detail?id=1112) created by Alexey-Yakovenko on 2014-05-14T07:03:51.000Z:

Если плеер закрыть вручную, то он запоминает позицию и при следующем запуске начинает воспроизведение с этой позиции. Это отлично.

Но если плеер закрылся автоматически при завершении сеанса (завершение работы с компьютером), то он не запоминает позицию воспроизведения.

Версия плеера: 0.6.0
Система: xubuntu 13.04 i386

**Comment by Soukyuu** [comment]
Sorry for not writing in Russian, but that would take ages without a Russian keyboard. 

Another possible solution would be to use [systemd-inhibit](http://www.freedesktop.org/wiki/Software/systemd/inhibit/) with a `shutdown` lock of the type `delay`, which would allow ddb to save the config, then remove the lock once it is done to allow the system to shutdown/sleep.

Also, the link to this issue on the FAQ page is still pointing to the issue number of the googlecode tracker instead of 1014.

**Comment by Alexey-Yakovenko** [comment]
systemd has the same problem as any other linux solution -- not guaranteed to be present / supported on the user's software combination.

updated the bug link in the FAQ.

**Comment by Soukyuu** [comment]
You will never be able to use one standard implementation on linux because linux is about freedom of choice - there will always be at least one alternative that does things differently.

systemd is the init system on nearly every up-to-date distribution I know (except for ubuntu, I guess, but even that has support for systemd starting with vivid afaik). Going this route makes the approach DE-independent, so that's one roadblock out of the way. 

The article I linked states that the program should not rely on being able to obtain the lock, so you could at least implement it to be used when available. Those not running systemd would just see the current behavior, and you could state you don't officially support other init systems just like you do with pulseaudio.

**Comment by Alexey-Yakovenko** [comment]
If I ever start using a linux distribution which has systemd in it - I might consider implementing such feature.

**Comment by yaeuge** [comment]
Maybe this remark is redundant, but the state is not saved if closing deadbeef with `kill $(pidof deadbeef)` or when pressing `Ctrl+C` in terminal. Restoring current track is not critical for me, but sometimes I need to edit tags of dozens of tracks, which are not saved after killing either. This problem becomes more annoying when deadbeef is set to minimize itself to tray on pressing close button instead of closing -- I just forget to exit it every time I shutdown my PC...
I do not know anything about programming for Linux, but I saw lots of examples when program performs some actions after being killed.
Thank you in advance!

**Comment by Alexey-Yakovenko** [comment]
> the state is not saved if closing deadbeef with kill $(pidof deadbeef) or when pressing Ctrl+C in terminal.

This behavior is intentional. Deadbeef is not supposed to be saving anything if it's terminated via kill/ctrl+c.

> Restoring current track is not critical for me, but sometimes I need to edit tags of dozens of tracks, which are not saved after killing either.

This information is supposed to be saved as soon as it changes in the player UI.
There are still quite many cases, when save doesn't happen.

Please try the latest build of deadbeef, and if you can reproduce the issue there - report a new bug.

**Comment by yaeuge** [comment]
> This behavior is intentional. Deadbeef is not supposed to be saving anything if it's terminated via kill/ctrl+c.
Could you please explain why?..
> Please try the latest build
Do you mean 0.7.2 release or the latest commit in master branch?

**Comment by Alexey-Yakovenko** [comment]
> Could you please explain why?..

Because kill signal can be sent during X11 shutdown, be handled by GTK, and terminate the process before the app can finish writing data to the file, resulting in corrupted files.

But that's not really important. The player is supposed to save its state as soon as it changes, not during exit.

> Do you mean 0.7.2 release or the latest commit in master branch?

I mean master branch: https://sourceforge.net/projects/deadbeef/files/travis/linux/

**Comment by BladeMight** [comment]
> If I ever start using a linux distribution which has systemd in it - I might consider implementing such feature.

So any updates on this? Or any other workarounds? Something like using `--quit` switch on session logout, or saving play session configuration every X seconds?

**Comment by Alexey-Yakovenko** [comment]
@BladeMight nobody was/is working on this

**Comment by Alexey-Yakovenko** [comment]
Closing because of irrelevancy. Deadbeef is supposed to save state as soon as it changes. Please report issues about individual cases, if needed.
