### ISSUE TITLE
Songs ratings and playcount as POPM fields

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [DeaDBeeF-Player/deadbeef#1143]
Original [issue 1241](https://code.google.com/p/ddb/issues/detail?id=1241) created by Alexey-Yakovenko on 2014-12-01T21:25:54.000Z:

I don't know all the songs I have in my library, I used ratings to remember what I like.
Sometimes, via random shuffle, I stumble upon a song I like and it's very useful to be able to rate them! Especially when listening to tracks I can't read nor pronounce (russian, chinese, etc.).

It's also easier to locate which songs from an artist I already like, a single glance and it's done.

**Comment by influenza** [comment]
+1 Same use case. With large music libraries it's *critical* to have a means of tagging songs as "this is great" or "this one isn't so good" - i.e., ratings.

**Comment by sonchusarvesis** [comment]
Pardon my asking, but can deadbeef read the POPM tag?
I have some issues with ratings between different players.

**Comment by Alexey-Yakovenko** [comment]
@sonchusarvesis deadbeef reads/writes entire ID3v2 tags, including POPM fields if they are present, but the content of this field is not displayed anywhere, and cannot be accessed from the existing UI.

**Comment by thangarajj** [comment]
Just installed deadbeef & it looks good :)
I've been looking for the rating option though & not able to find any way to rate songs. So adding support for this request.

**Comment by splushii** [comment]
Hi, I wanted this feature really bad so I made a simple [rating plugin](https://github.com/splushii/deadbeef-rating) for it =)

**Comment by Alexey-Yakovenko** [comment]
Thanks @splushii !
I'm sure many users would appreciate this!
I'll add the plugin to the wiki, and close this feature request.

**Comment by piotrwicijowski** [comment]
Unfortunately, for id3v2 tags, @splushii plugin stores the rating in "TXXX=rating" custom tag instead of "POPM" tag, so it is unfortunately incompatible with most of other music players.

**Comment by Alexey-Yakovenko** [comment]
@piotrwicijowski I will look into adding POPM support. Can you name another music player, which supports POPM correctly, so that I could test the compatibility?

**Comment by piotrwicijowski** [comment]
@Alexey-Yakovenko Apparently, the general problem of "rating in POPM tag" and scaling it to star values is much more complicated than it seems, mostly because this approach is non-standard (according to id3v2 spec). However, most media players seem to (roughly) agree on values read/set by windows media player. A very detailed discussion of POPM tag values and their correspondence to 0-5 star rating can be found here: http://www.mediamonkey.com/forum/viewtopic.php?f=7&t=40532

As for ways of checking the POPM value/reading the rating value, there are several options

windows:
- windows media player
- windows explorer - does not seem to read id3v2 version 2.4, 2.3 works ok
- foobar - is not displayed by default in the ui, but to access it one must add a user-defined column with `$meta(rating)` value.

linux:
- banshee - the rating id3v2 value is read only during initial import of the files to database, after that all modifications of the rating are done internally without touching the file tags. For testing, adding and removing tracks from database over and over can be tedious, so I guess this is not an option.
- clementine - displays the value in the tag editor interface (ctrl+E), somehow the rating column value in the playlist is taken from internal DB instead of file tags (bug https://github.com/clementine-player/Clementine/issues/3666). Caution - clementine does not seem to be able to save the rating to mp3 file.
- bash - below is a one-liner I use to extract the raw value of POPM rating from an mp3 file (requires mid3v2 utility):

    `mid3v2 --list-raw /path/to/file.mp3 | grep POPM | sed "s/.*rating=\([0-9]*\).*/\1/" `

- qoobar - it reads and writes the tag, but the scaling between 1-5 (display) and 0-255 (POPM value) is significantly different from all of the above. The mapping seems to be the following:

Rating | POPM raw value (as set by qoobar)
------------ | -------------
1 | 19
2 | 78
3 | 137
4 | 196
5 | 255

In the end, I think the most reasonable way would be to stick to the predominant mapping that originates from windows media player:

rating| writes|reads 
-------| -----|-----------
1      |     1|   (1-31)  
2      |   64|  (32-95)  
3      | 128| (96-159)  
4      | 196|(160-221)  
5      | 255|(222-255)  

and if we would like to have support for half-star increments (and also include 0.5 rating), the suggested approach for mediamonkey player (from the link in the first paragraph of my comment) could be used:

 rating |  POPM
-------|  --------
0      |        0
0.5    |     2-22
1      | 1, 23-31
1.5    |    32-63
2      |    64-95
2.5    |   96-127
3      |  128-159
3.5    |  160-195
4      |  196-223
4.5    |  224-254
5      |      255

**Comment by Alexey-Yakovenko** [comment]
@piotrwicijowski thanks for the detailed break down!

I'm reopening this request with the better title

**Comment by ropeladder** [comment]
Like Clementine, Foobar2000 stores ratings and playcount data in a separate database without writing to the files themselves, using the [foo_playcount](http://wiki.hydrogenaud.io/index.php?title=Foobar2000:Components/Playback_Statistics_v3.x_%28foo_playcount%29) plugin. Something like this with an XML import would be ideal for me since I have years of data from f2k and would prefer not to write to all my files.

**Comment by Alexey-Yakovenko** [comment]
@ropeladder this feature request is about adding native support of ID3v2 POPM field. It doesn't really cross with media library.

**Comment by bro1** [comment]
I have started looking at the code and specification. It looks like specification allows to have more than 1 POPM tag: "There may be more than one "POPM" frame in each tag, but only one with the same email address."

**Comment by kpcee** [comment]
The POPM frame is explained at [id3.org](http://id3.org/id3v2.3.0#Popularimeter). Just define a default email address for DeaDBeeF and you could work with it. Can a plug-in access the POPM frames via the API? In this case an adjustment of the plug-in should not be very extensive. 
The implementation can be tested with the great Kid3 tagger or with Quod Libet, both support the popularimeter.

**Comment by Alexey-Yakovenko** [comment]
Yeah plugins can access everything in ID3v2, so creating such plugin is technically possible.

**Comment by kpcee** [comment]
I made some minor changes to the rating plugin. If deadbeef supports POPM correctly at some point I will try to add it there as well.
![Unbenannt](https://user-images.githubusercontent.com/39984895/58944575-a58c4b80-8771-11e9-8f32-7cf6e817f338.png)

**Comment by Alexey-Yakovenko** [comment]
@kpcee Does your rating plugin do anything special if it encounters multiple POPM fields in the tag?

**Comment by kpcee** [comment]
The plugin uses a proprietary frame called "rating" for saving, it uses no POPM frames. If there is a change it will be necessary that the plugin migrate the existing ratings. Since every POPM frame has its own ID, it might be a good idea to use a special ID for DeaDBeeF.

**Comment by Alexey-Yakovenko** [comment]
It doesn't seem practical to me to introduce a new ID (email).
I know it's not what was intended by id3v2 creators, but reality is such that all players write WMP rating to stay compatible and share the rating info.

**Comment by Alexey-Yakovenko** [comment]
> If there is a change it will be necessary that the plugin migrate the existing ratings.

There won't be need for migration. The rating field will be automatically used, and will be written as POPM on next edit.

**Comment by Alexey-Yakovenko** [comment]
My current idea is this:

On read:
* All POPM fields will be loaded in order, and replace each other
* POPM with WMP ID will take priority over any other IDs - that is, if WMP POPM is present, all other POPM will be ignored
* When multiple POPM frames with WMP ID are encountered, only one will be used, most likely the first one
* TXXX field will take priority and overwrite any POPM

When writing:
* Remove all WMP POPM frames, and write a single one with the rating value
* Keep any POPM frames with non-WMP ID

**Comment by kpcee** [comment]
Okay but POPM and the previous rating are not compatible. POPM has values between 0-255, the current plugin works with 0-5, that must DeaDBeeF automatically convert and delete the old rating frame. Can the POPM frame accessed with %rating% and works with the present values or with 0-255?

**Comment by Alexey-Yakovenko** [comment]
Yeah, sorry I didn't mention this, but the POPM value will be remapped to 0..5 range before putting it into rating field, and then back to 0..255 on write. Something similar will possibly be needed for other tag formats.

**Comment by kpcee** [comment]
That sounds great.

**Comment by Gooberpatrol66** [comment]
I'm confused. How do I show or edit ratings? Do I have to install splushii's plugin?

**Comment by Alexey-Yakovenko** [comment]
Yes, just follow the README here https://github.com/splushii/deadbeef-rating
