### ISSUE TITLE
removing playlist while the next track is buffering leads to GUI inconsistency

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [DeaDBeeF-Player/deadbeef#1178]
Original [issue 1276](https://code.google.com/p/ddb/issues/detail?id=1276) created by Alexey-Yakovenko on 2015-02-17T11:43:19.000Z:

<b>What steps will reproduce the problem?</b>
1. play any track
2. wait until the next tracks starts buffering (&lt;5 sec before the end of the current track)
3. delete the current playlist

<b>What is the expected output? What do you see instead?</b>

Should cancel the buffering, and pick next track from the new current playlist.
Instead, the next track from the deleted playlist starts playing, and when it finishes, playback stops, but the seekbar stays black, instead of inactive state.

<b>Please use labels and text to provide additional information.</b>

reported by starws, unconfirmed.

**Comment by L2-D2** [comment]
I just compiled the current code and this bug is still (mostly) there.

Deleting the current playlist during buffering plays only the next track from the deleted playlist after, then stops.

The seek bar does stay black for a tick, but resets to the aforementioned inactive state.

What is the actual expected result? I'd like to poke around with this if I had a clear idea of what the desired behavior would be..

My thought would be just have the player stop in this instance.. but perhaps there's so much demand for closing a playlist playing the next playlist's songs....

Anywho thanks, nice to talk to you

**Comment by oleksiy-unity3d** [comment]
Thanks for the update.

**Comment by Alexey-Yakovenko** [comment]
This issue is really hard to handle properly, since there's no going back after the track already started buffering / being decoded.

The only valid solution I came up with is like this:

* Detect that a track or playlist was deleted
* Check if the buffering track is the same as playing
* If it isn't, cancel the buffering, and flush all decoded blocks of the next track(s)
* Find the new next track, and start streaming it instead

**Comment by Alexey-Yakovenko** [comment]
I implemented this approach. It may cause regressions, and I know quite a few edge cases where it would still not work as expected, but they are not worth to be handled.
