### ISSUE TITLE
converter: potential problems may happen from file size approximation

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [DeaDBeeF-Player/deadbeef#1229]
Moved from issue #1139  (reported by @Lithopsian)

The file length placed in the RIFF header is an approximation when a pipe is used, since it is calculated in advance rather than being an actual file size. It is often wrong for Flac files because their playitems don't contain an endsample except from cuesheets (should they, it looks easy?), but also for output through DSP where samplerate changes can cause rounding errors. This doesn't cause problems for any encoders I've tested with, but they have to be set to ignore header sizes anyway. With a temporary file, the chunk size is written in after completion and is exact, but the RIFF file size is still left as an approximation which means RIFF WAV output files are sometimes technically invalid, although I haven't found a player that refuses to play them. Some tools do report header problems.

When encoding through a pipe, four spurious bytes are written to the pipe at the end of the audio data. This is because the converter tries to fill in the correct chunk size in the temporary file, but seeking in a pipe fails and the bytes are just appended. I imagine this data will be discarded in most cases since it won't form a complete sample (Flac warns about this extra data if it is given the chunk size and the --ignore-chunk-size parameter is not set), but for 8 bit or mono it would look like a sample and since the chunk size is zero the encoder cannot know it is garbage.

**Comment by Lithopsian** [comment]
The converter has a check to not write the four header length bytes if it using a pipe, because obviously it won't be able to write them in the correct place.  Is this not working in all cases?  See the if statement on line 1095 (trunk, as of Sep 21st).  It is a bit convoluted because the pipe handle is also stored in the temp_file variable, but it seems like it works OK.

When I rewrote the converter, I didn't fill in the approximate length at all, just the exact length at the end for temporary files.  Better that it be zero than something that looked valid but was often wrong.  Some tools were reporting the header not matching the audio data, but I don't remember if they were ever ignoring some valid audio data because the header size was only slightly wrong.  Now encoders that look at the header size either know it is meaningless, or must have an option set to ignore it, with no possibility of confusion.  Note that there are two lengths, one the length of the whole file, and one the length of the audio chunk.  I think the converter only back-fills one of them.

**Comment by Alexey-Yakovenko** [comment]
Do I need to reply to this in any way, or this is just a "FYI"?

**Comment by Lithopsian** [comment]
Mostly just FYI.  Unless someone complains about it, it is just ideas for one day in the future.

**Comment by Lithopsian** [comment]
Also I didn't realise until after I'd written, that I was just replying to myself :)

**Comment by Alexey-Yakovenko** [comment]
hahaha! yeah, that's what I thought :)

**Comment by Alexey-Yakovenko** [comment]
no actionable, closing.
