### ISSUE TITLE
[Support] Playing webm files

### ISSUE THREAD

**Issue by aviaryan** [DeaDBeeF-Player/deadbeef#1511]
Sorry for putting this up here but I wasn't able to find another place to ask for support. 
The issue is Deadbeef doesn't detect *.webm audio files. I looked up in the plugins page and didn't find a related plugin. 

Thanks for any help.

PS - Foobar supports webm files.

**Comment by Alexey-Yakovenko** [comment]
Deadbeef doesn't support webm files.

**Comment by xinyazhang** [comment]
Actually most known formats can be played through ffmpeg plugin.
Preferences->Plugins->FFMPEG audio player->Configure allows adding new extensions without hacking into the code.

However since there is a request I'd like to add webm to the ffmpeg plugin to close this.

**Comment by Alexey-Yakovenko** [comment]
@xinyazhang I disagree that request is good enough reason for adding something. See my comment in the PR.

**Comment by xinyazhang** [comment]
@Alexey-Yakovenko got it, you're right.
I'll seek for alternatives.

**Comment by nick87720z** [comment]
It could be possible to add all audio formats, supported by ffmpeg. I'm only not sure, if '-formats' output could be treated as file extensions.
https://superuser.com/questions/649327/what-file-extensions-does-ffmpeg-support

Need to check for reliable way - my `ffmpeg -formats` has formats names, for webm it's webm, but for mkv - only 'matroska'.

**Comment by Alexey-Yakovenko** [comment]
This is not a very viable option. Deadbeef relies on ffmpeg libraries, not on ffmpeg command line utility. We can't rely on the utility to be present.

OTOH, deadbeef already has an option in the ffmpeg plugin to enable "all supported formats", although enabling this option may cause issues which can't be resolved on deadbeef side, and therefore is off by default.

**Comment by nick87720z** [comment]
I exactly meaned to support all ffmpeg file extensions as best way to add missing audio file formats :)
As for shell script - I used it only to check, if ffmpeg able to provide necessary information, did not meaned to use script way. Did not even know about such option.

IMHO, that solves this issue. As for inability to make it default on, there could be FAQ entry for common "missing ffmpeg format" question.

**Comment by CouponCodeSwap** [comment]
To reiterate and expand upon what was stated in this comment: https://github.com/DeaDBeeF-Player/deadbeef/issues/1779#issuecomment-742651110

I think webm support is important as there are a probably lot of people using youtube-dl to download audio files in opus format (for maximum quality / lack of encumbering proprietary license or royalty fees associated with the format) and the opus files downloaded from youtube are opus in webm container. I have been using DeaDBeeF since I can't remember when and it is one of my favorite audio players, thus I would like to submit my vote for adding webm support.

**Comment by saivert** [comment]
In that case you run `youtube-dl -x` which extracts the audio from the container and gives you a proper .opus file. Not opus inside webm container.

**Comment by CouponCodeSwap** [comment]
> In that case you run `youtube-dl -x` which extracts the audio from the container and gives you a proper .opus file. Not opus inside webm container.

I run youtube-dl with the -x switch and the resulting opus files do not play in DeadBeeF.

**Comment by saivert** [comment]
Then you are doing something wrong. I just tried now and I get a proper Ogg OPUS file in the end after using `youtube-dl -x `

https://saivert.com/files/deadbeef-opus-working.png

**Comment by CouponCodeSwap** [comment]
I am not doing something wrong. Just to confirm I ran:

`$ youtube-dl -x 'https://www.youtube.com/watch?v=eRIatotHqMA'
[youtube] eRIatotHqMA: Downloading webpage
[download] Destination: Ferry Corsten - Tomorrow-eRIatotHqMA.webm
[download] 100% of 4.11MiB in 00:02
[ffmpeg] Destination: Ferry Corsten - Tomorrow-eRIatotHqMA.opus
Deleting original file Ferry Corsten - Tomorrow-eRIatotHqMA.webm (pass -k to keep)`

The opus file is successfully created, as usual. However, Ferry Corsten - Tomorrow-eRIatotHqMA.opus does not play.

The only relevant line in the DeaDBeeF log that pops up is:

> failed to add file or folder ~/Ferry Corsten - Tomorrow-eRIatotHqMA.opus

P.S. ffmpeg 2:4.3.1-3 is installed

**Comment by Alexey-Yakovenko** [comment]
@CouponCodeSwap 
it works for me, I used the same command as you.
it produces a normal ogg opus file, which plays in deadbeef, without using ffmpeg.
I think you have some bad deadbeef build.

**Comment by Alexey-Yakovenko** [comment]
> (What is the BB code for pre element on github?)

there's no bbcode.
Click the little "M↓" icon in the bottom right corner of the text field to get markdown help.

**Comment by CouponCodeSwap** [comment]
> @CouponCodeSwap
> it works for me, I used the same command as you.
> it produces a normal ogg opus file, which plays in deadbeef, without using ffmpeg.
> I think you have some bad deadbeef build.

I recently got a new laptop and vaguely remember dealing with this issue ~ 1-3 years ago. I'll fire up the old laptop and test if I am able to play opus files in DeaDBeeF on there. If I did figure out a way to get it working, unfortunately there are no notes in my Arch install cheat sheet nor in the hacks folder. All I have in the cheat sheet is this:

> faad2 : for AAC/MP4 support	deadbeef
> libmad : for MP1/MP2/MP3 playback	deadbeef

Those two are already installed.

The build I am using:

https://www.archlinux.org/packages/community/x86_64/deadbeef/

**Comment by saivert** [comment]
Checking their PKGBUILD I don't see opus in makedepends so looks like it builds without opus support. You should file a bug.

**Comment by CouponCodeSwap** [comment]
> Checking their PKGBUILD I don't see opus in makedepends so looks like it builds without opus support. You should file a bug on https://bugs.archlinux.org/

Getting somewhere… I do have it working on the old laptop. Also tested on a Macbook Air which had Arch installed around the same time as old laptop and it doesn't play. You beat me to it, the notes in my cheat sheet about faad2 libmad was a clue that I need to manually install support for opus as well. Because I was not disciplined about updating the cheat sheet after getting opus working the last time, I wasted time on this again. I'm guessing the reason opus plays in all other players is that they are using ffmpeg for opus support.

**Comment by CouponCodeSwap** [comment]
I already have opus 1.3.1-2 installed, so I guess it needs to be baked in when DeaDBeeF is compiled. Looks like I need to scrounge something up from AUR.

**Comment by CouponCodeSwap** [comment]
> I already have opus 1.3.1-2 installed, so I guess it needs to be baked in when DeaDBeeF is compiled. Looks like I need to scrounge something up from AUR.

Nope, that ain't it. deadbeef-git from AUR doesn't play opus either. I checked the old laptop again, it is the official deadbeef 1.8.4-1 from community repos. The only thing I see is that opus; is added to ffmpeg File Extensions, which I have already tried. What in the world did I do before to get this working? This is driving me nuts! There must be some codec dependency that is not yet installed…

**Comment by Alexey-Yakovenko** [comment]
you need to install the opus library: libopusfile (+dependencies)

**Comment by Alexey-Yakovenko** [comment]
You should not add opus to ffmpeg. This is generally a "worse" library to play opus files in deadbeef, than the native support.
If you can't get opus to play using arch packages from repositories -- you could try using the arch package provided on deadbeef website.

**Comment by Alexey-Yakovenko** [comment]
The error you posted indicates you didn't have any input plugin in deadbeef, that could play opus files.
ALSA or Pulse don't have anything to do with it :)
Probably just a coincidence that when you switched to Pulse, you also found how to make the ffmpeg (or opus) plugin to work.
You can find out which one is used in the track properties.
Anyway, great to hear you nailed it. It's way easier to just use the official deadbeef builds, which include the opus codec, among others, and don't require such extensive research and trial and error to make it work.

**Comment by CouponCodeSwap** [comment]
I switched back to ALSA output plugin and DeadBeef reverts back to not playing opus files, it is not a coincidence. I guess building from git myself is the recommended install method since even the recently updated deadbeef-git from AUR does not work. I'll try that later and let you know if it solves the issue, this has already consumed an entire morning and it is time to move on to other more pressing tasks with some soothing music playing in the background. Thank you for all the help!

**Comment by Alexey-Yakovenko** [comment]
Why should it be recommended to build anything by yourself if you could just download prebuilt binaries?
But anyway, do whatever is best for you.

**Comment by CouponCodeSwap** [comment]
Okay, couldn't leave this alone, had to scratch one more itch. If I set it back to ALSA output plugin and then switch Default Audio Device to HD-Audio Generic, HDMI 0. I am then able to play opus files ALSA output plugin.

Another observation, if I already have an opus file in the playlist and remove opus; from ffmpeg File Extensions, I can still play the file. However, if I close DeaDBeeF I am not able to open with opus files to DeaDBeef, I am not able to drag and drop opus files to playlist after opening DeaDBeeF and opus files don't even show up in the File > Open file(s) window.

**Comment by Alexey-Yakovenko** [comment]
Just tried on ubuntu, downloaded a random build of deadbeef, and played a random opus file with ALSA plugin. Works just fine. Didn't configure anything.

![image](https://user-images.githubusercontent.com/1895698/101958866-7f682700-3c04-11eb-9e15-882179b57003.png)

**Comment by Alexey-Yakovenko** [comment]
> I am not able to drag and drop opus files to playlist after opening DeaDBeeF and opus files don't even show up in the File > Open file(s) window

This means that you don't have the opus plugin installed, or it can't load because libopus/libopusfile/whatever is not installed.

**Comment by Alexey-Yakovenko** [comment]
Sorry clicked close by accident :)

**Comment by CouponCodeSwap** [comment]
The only option for "libopus" in community and AUR is libopusenc. I installed that and it did not solve the issue, didn't expect it to. Perhaps there is another opus codec I have not found yet? I already have opus 1.3.1-2 installed:

https://www.archlinux.org/packages/extra/x86_64/opus/

Is it possible DeaDBeeF is not recognizing it because it is not called libopus? Found some others that look promising. Going to try adding opusfile and if that does not solve it, opus-tools…

**Comment by CouponCodeSwap** [comment]
Neither opusfile nor opus-tools resolved the issue. I don't see anything else “opus” related to try installing. I think it might be what I mentioned earlier about DeaDBeeF not recognizing it because it is not “libopus”.

**Comment by Alexey-Yakovenko** [comment]
I'm quite sure that @saivert is correct, and the packages you are using / compiling do not build opus support in deadbeef.
In this case, you have these options:
* Download the deadbeef binaries or Arch package from deadbeef website - they "just work".
* Fix the Arch package specs to enable opus and rebuild it locally
* Build deadbeef manually, making sure opus support is enabled
* Do as you did and configure deadbeef to use ffmpeg for opus - but this is really the worst option. Although if you only use that for playing music rips from youtube -- it should work fine for this, and it's an easy way out if the first option is not acceptable.

**Comment by CouponCodeSwap** [comment]
Holy cow! Downloaded the Arch package from https://deadbeef.sourceforge.io/download.html, installed… lo and behold, it "just works"!!

Not even going to ask why that package is not in the Arch community repos, I'm sure there is a “very good reason”.

I have never seen an Arch install offered like that before. On the rare occasion I do a manual install it is because an upgrade introduced unacceptable, unfixable bugs and I had to rollback to a previous version, manually installing a previous version from pacman cache or track it down online if the cache had been cleared.

Thanks again! Learned something new and glad I will no longer be listening with a subpar ffmpeg opus codec experience due to the hack I had figured out earlier to get opus working via the plugin settings.

**Comment by CouponCodeSwap** [comment]
@Alexey-Yakovenko @saivert I'd like to send you guys a tip with BAT funds but it doesn't look like you signed up for that yet. If you sign up, I'll get that sent. If not, is there another way to donate?

**Comment by CouponCodeSwap** [comment]
Bug filed: https://bugs.archlinux.org/task/68959

**Comment by Alexey-Yakovenko** [comment]
This doesn't seem to be actionable

**Comment by TroubledPerson** [comment]
FFMPEG in DeaDBeeF is very old like 10 years old. Possibly if the FFMPEG plugin gets updated it might support Webm. As currently Webm still refuses to be played

**Comment by Oleksiy-Yakovenko** [comment]
It's not true, deadbeef uses new-ish ffmpeg, and supports 5.x.
You can build deadbeef with whatever ffmpeg version you want.
However, the "built-in" ffmpeg does not include webm support.
It has nothing to do with age. It's also relatively easy to enable. Just not quite high priority.

**Comment by TroubledPerson** [comment]
deadbeef should still update ffmpeg in the main builds tho. But it's not important as it's just one file type

But yeah I will still build it with a later version of ffmpeg.
