### ISSUE TITLE
Hotkey doesn't work

### ISSUE THREAD

**Issue by malcolm061990** [DeaDBeeF-Player/deadbeef#1913]
### Steps to reproduce the problem
I changed some default hotkeys. For example, I want to have an action "Play" by pressing keys LCtrl+LAlt+Insert.
### What's going on? Describe the problem in as much detail as possible.
This hotkeys don't work. Nothing happens when I push it.
At Ubuntu 17.04 and previous versions it worked!
### Information about the software:

Deadbeef version: 0.7.2
OS: Ubuntu 17.10

**Comment by Alexey-Yakovenko** [comment]
There are a few things that you may try:

* Run `xev` in gnome-terminal, press your desired key combination, and inspect the output. It will probably look wrong, but you won't be able to tell. So post it here, and we can look together.
* Try running another desktop environment, e.g. by installing openbox or kde or whatever, and see if this fixes the issue.

When you find which particular software prevents deadbeef from receiving those key events -- you may want to report the bug to them, instead of here.
It's quite obvious, that since deadbeef didn't change - something else causes the issue.
