### ISSUE TITLE
100% CPU load by deadbeef-alsa since recent update

### ISSUE THREAD

**Issue by cbirchinger** [DeaDBeeF-Player/deadbeef#1927]
A very recent update on the 8. Nov. 2017 causes the ALSA plugin to use 100% CPU load
on a single thread (deadbeef-alsa). It does not matter what kind of device is being used.
I've tried onboard intel-hda, usb audio 2.0, xonar pci-e card and AMD HDMI, so i doubt
it's hardware dependent.

So started going back to older versions of "alsa.c". Everything else remains the latest
git release.

First version of alsa.c with problems:
Nov 8, 2017  "alsa: fixed error handling / locking" (8b8d5cd218aeec4b322b04111e851883c49ea670)

Last working version:
Nov 7 2017 "alsa: refactored code with better error handling and attempts to fix" (91124bf7e33816652793d43e4756b8add1c839f8)

Deadbeef version: latest git (22. Nov. 2017)
OS: Gentoo Linux (alsa-lib 1.1.2, alsa-plugins-1.1.1, Linux kernel 4.9.64)

If you suspect that newer alsa-libs are required, would the alsa.c plugin 
from the 7. Oct. 2017 be a good version for me to switch back as it
seems to be a good version before a larger rewrite?

**Comment by Alexey-Yakovenko** [comment]
I suggest using the revision which works best for you. I'll look into this issue as soon as possible.

**Comment by Lithopsian** [comment]
I see it too.  Uncontrolled looping at line 617.  Probably just needs a short sleep.

**Comment by DaarkWel** [comment]
Same here, kinda annoying.
I tried with alsa.c version 91124bf and it works without high cpu load but presented some sound glitches every minute or so. Maybe because I'm using system-wide alsa-jack plugin, but with latest alsa.c version there's no glitches, yet there is 100% cpu load.

**Comment by JulianLai** [comment]
Same here with deadbeef-git r7562.2f471821-1

**Comment by wdlkmpx** [comment]
I also see this issue.. the problem seems to be gone if i insert ```usleep (10000);``` in line 625

**Comment by Bfgeshka** [comment]
Problem bugs be a bit too. OSS output is ok as workaround, but OSS to ALSA bridge works not so good with mixing.

**Comment by JulianLai** [comment]
@Alexey-Yakovenko wdlkmpx says that he has solved the problem.

**Comment by Alexey-Yakovenko** [comment]
Sorry, I didn't have much time to fix this.

I'm not confident that this is the right solution to the problem, but I'm adding a sleep as a temporary workaround.

**Comment by JulianLai** [comment]
It seems that it isn't the right solution to fix the problem, the music will be stuttering if I play a 192kzh audio file, no matter how big the buffer is.

**Comment by Alexey-Yakovenko** [comment]
This is exactly why I didn't want to add the sleep fix.

**Comment by Alexey-Yakovenko** [comment]
changing 10000 to a smaller value should make it work with 192K though.

**Comment by wdlkmpx** [comment]
Oops sorry i didn't test with a 192khz audio file.. i'll be testing with some hires audio files and open a PR with a more reasonable sleep time (was just following the advice posted above)

**Comment by Alexey-Yakovenko** [comment]
I can't find any obvious way to calculate how much time do we really need to sleep before ALSA buffer is ready, therefore I'm just putting in a generic value of 1000 µsec, which should be low enough.

Btw, 10000 is definitely too high even for running at 48KHz when running in virtualbox, as processing takes more time in a VM.

A fundamental problem here is that on slower machines we need to sleep less, or not sleep at all, while on fast machines we need to sleep about as much as period size, i.e. the time of 1024 samples, which translates roughly to 21000 µsec at 48KHz. But we don't know exactly how much is needed, and the guesswork will always be wrong.

I already tried many approaches to run alsa loop, and all of them suffer from this same problem -- inability to calculate precise number of sleep amount.

So perhaps the next thing to try would be using `snd_async_add_pcm_handler`, as demonstrated [here](http://www.alsa-project.org/alsa-doc/alsa-lib/_2test_2pcm_8c-example.html). Or.. read ALSA sources and figure out how it drives the async_callback, as this seems to be exactly what we need.

**Comment by Lithopsian** [comment]
Apparently Alsa async is not very practical, buggy and poor device support.  As in it just doesn't work with many devices.

Without changing anything very much, it should be possible to approximate the right sleep length, but not with snd_pcm_avail_update() because it doesn't sync with the underlying ring buffer so it doesn't update avail smoothly.  I tested with snd_pcm_avail() which syncs and then returns the available slots.  Starting with sleep_usecs = 10, I doubled it whenever avail < period_size/2.  The sleep interval rapidly reached one sleep per read, although you might want to be less aggressive in practice.  snd_pcm_avail() is slower than snd_pcm_avail_update() but it will be called far fewer times.  Of course working reliably is the main thing.

There are other ways to poll or wait in Alsa but some of them are too simplistic for Deadbeef.  Have you tried the native poll() function?

**Comment by Alexey-Yakovenko** [comment]
@Lithopsian I haven't tried poll. Any pointers how to use it with ALSA?

**Comment by Lithopsian** [comment]
Alsa has an example file:
https://www.alsa-project.org/alsa-doc/alsa-lib/_2test_2pcm_8c-example.html

It shows both poll() waiting and an async callback.  poll() can be used to wait on multiple descriptors and possibly handle both read and write in parallel on the same thread, but in this example it is just used to wait for space in the buffer before calling snd_pcm_writei().  It can be used as a direct replacement for usleep().  It will normally return when the buffer has at least one period free because that's when an interrupt is generated.  You would probably want to check snd_pcm_avail_update() anyway because it is easy and avoids having to handle partial buffers, but in my tests it always seems to return with avail at 1024 (actually 1025 or 1026 after a full check).  Seems worth a try.  For me at least, it seems to avoid the blocking from other threads that has been causing some audible glitches - the poll() interrupt seems to always happen very quickly.

**Comment by Alexey-Yakovenko** [comment]
Thanks. If I understood the docs correctly, they state that snd_pcm_avail / update needs to be called either way before writing, no matter whether poll is used or not. I will try it out soon.

**Comment by Lithopsian** [comment]
I don't think you *have* to call snd_pcm_avail_update().  It doesn't actually do anything except return a value from a structure.  Still, it seems like some Alsa drivers generate events all over the place instead of just at the end of a period, especially virtual ones and when Alsa is resampling.  So some sort of checking is useful to avoid dealing with partial writes, and also a short sleep to avoid thrashing when a driver occasionally gets its internal event timer badly wrong.

poll() also returns POLLERR before alsa_terminate is set, at least the way Deadbeef is set up.  Then snd_pcm_avail() will return -77 (EBADFD), although snd_pcm_avail_update() will keep returning whatever value it had at the time.

Here's a simple wait loop that works for me:
```
        do {
            poll(ufds, count, -1);
            LOCK;
            snd_pcm_poll_descriptors_revents(audio, ufds, count, &revents);
            UNLOCK;
            if (revents & POLLERR) {
                printf("POLLERR\n");
                break;
            }
            if (revents & POLLOUT) {
                LOCK;
                int really_avail = snd_pcm_avail(audio);
                UNLOCK;
                if (really_avail < 0 || really_avail >= period_size)
                    break;
                printf("avail = %d/%d, alsa_terminate=%d\n", really_avail, period_size, alsa_terminate);
            }
            else {
                printf("Unexpected event\n");
            }
            usleep(100);
        } while (1);


```
