### ISSUE TITLE
Is the version 0.8 coming?

### ISSUE THREAD

**Issue by JulianLai** [DeaDBeeF-Player/deadbeef#1945]

**Comment by Alexey-Yakovenko** [comment]
The next release is going to be called 1.8 instead.

**Comment by rindeal** [comment]
1. When can we expect that to happen?
2. Are there some blockers that need to be resolved?
3. Will it brake existing plugin API?

**Comment by Alexey-Yakovenko** [comment]
> When can we expect that to happen?

You don't need to wait -- feel free to use 1.8beta1. It has some unresolved issues, but it's usable.

We are working hard to make sure that 1.8 release is as good and stable as possible, so please be patient.

> Are there some blockers that need to be resolved?

Yes, there are a few. Most notably the ALSA hang bug. So if you're gonna give the beta1 a try -- please choose PulseAudio output over ALSA for now.

> Will it brake existing plugin API?

Most existing plugins are expected to keep working, and won't require recompiling.

However, because of some very big changes of how stuff works internally, some plugins may expected to stop working correctly.

This mostly affects 3rd party audio output plugins, so nothing to worry -- there are not that many of them.

**Comment by rindeal** [comment]
Ok, thanks. I was asking primarily to set a timeline for a migration of my distro packages. But as it's entered beta phase already, I'll give it a go. Could you also please tag the beta releases in git so that I can track changes among them more easily?
