### ISSUE TITLE
Will there be a newer version of DeaDBeeF in snap or flatpak format?

### ISSUE THREAD

**Issue by laichiaheng** [DeaDBeeF-Player/deadbeef#2054]
### Steps to reproduce the problem
The snap version of DeaDBeeF is still in 0.7.2
### What's going on? Describe the problem in as much detail as possible.
It is too ancient.
### Information about the software:
0.7.2-snap2
Deadbeef version: 0.7.2-snap2
OS:Ubuntu 18.04

**Comment by Alexey-Yakovenko** [comment]
There was never an official build of deadbeef in snap or flatpak formats, and there are no plans to make them.

**Comment by BigmenPixel0** [comment]
> There was never an official build of deadbeef in snap or flatpak formats, and there are no plans to make them.

Hello! I [wrote](https://github.com/BigmenPixel0/custom-flatpaks/blob/master/net.sf.deadbeef.DeaDBeeF/net.sf.deadbeef.DeaDBeeF.yaml) a flatpak manifest, can I post DeaDBeeF on [flathub.org](https://flathub.org)?

**Comment by Alexey-Yakovenko** [comment]
@BigmenPixel0 
I can't really stop you from packaging and redistributing Deadbeef in whatever form you like.
The only thing that I would have liked is if such packages would have been marked as unofficial, since the users otherwise think that the flatpak / snap packages are coming from deadbeef developer team, and get confused when the application doesn't work correctly.

**Comment by ghost** [comment]
Sorry to bump this, but could there be consideration of doing a flatpak?  This would make it really easily available to everyone in a convenient package that can include frozen versions of dependencies and etc that's probably even more guaranteed to work correctly on a system (since you can control what it uses) than the static build alone.

It also could do some nice meta extras like setting file associations.  That's definitely not a fun process to do manually...

(I wouldn't bother with Snap.  Even Ubuntu users can install Flatpak and are better off by doing so.)

**Comment by Oleksiy-Yakovenko** [comment]
@Nazosan hey, sorry - probably not the answer you're looking for, but I haven't heard about any changes in this direction. I believe @saivert was doing some work on this, but I don't know the current state.

**Comment by Oleksiy-Yakovenko** [comment]
I searched, and found this -- so you can download a flatpak package from there:
https://github.com/saivert/deadbeef-flatpak/releases/tag/1.10.0-rev3

**Comment by ghost** [comment]
I guess I should modify my suggestion in that I mean it would be nice to see an official submission to Flathub itself rather than third party.

**Comment by Oleksiy-Yakovenko** [comment]
We still have some unresolved logistical problems with that. There were some discord discussions, but we still don't have a plan for this.

**Comment by jing2uo** [comment]
Hi — following up on this old thread, because there's now a Flatpak that I think sidesteps the specific problem you raised.

DeaDBeeF is listed on [FlatPark](https://flatpark.org/apps/io.sourceforge.deadbeef/) (`io.sourceforge.deadbeef`), a small independent Flatpak repository I maintain. It is **not** a rebuild from source, and it does not substitute any dependency: the package is `extra-data`, so at install time Flatpak downloads **your official portable Linux build** — the exact `deadbeef-static_<version>_x86_64.tar.bz2` from SourceForge, checksum-pinned — and unpacks it. The wrapper then just points `DEADBEEF_PLUGIN_DIR` and `LD_LIBRARY_PATH` at that tree and execs your binary. So what a user runs is the same static build you already ship, and the bundled-dependency behaviour you control stays intact.

On your "please mark it unofficial" point — agreed, and it's marked in both places a user actually looks. The listing carries no developer-approved badge, and the AppStream description opens with: *"This is a community package of DeaDBeeF, maintained independently and unaffiliated with the DeaDBeeF project. It repackages the official upstream Linux portable build unmodified."*

What the package adds on top of the tarball is the desktop-integration glue @Nazosan asked about: a desktop entry with the audio MIME associations (mp3/flac/ogg/opus/wav/ape/wv/m4a/wma/cue/m3u), the icon, AppStream metadata, MPRIS2 and desktop notifications, PulseAudio/PipeWire and Wayland/X11 sockets. Sandbox defaults are narrow — `xdg-music` only; `--filesystem=home`, GVfs mounts, and the `~/.local/lib64/deadbeef` user-plugin directories are documented as opt-in overrides rather than granted by default.

It also won't go stale the way the old snap did: an update resolver reads `deadbeef.sourceforge.io/download.html` and picks up new stable builds automatically (currently 1.10.3). x86_64 only, since that's what the portable build targets.

Two things I'd like from you, both entirely your call:

1. If you're fine with it existing on these terms, I'd be glad to link it as an unofficial-but-endorsed install option — and if you'd rather it stay unmentioned, that's fine too.
2. If you'd prefer it not exist at all, say so and I'll de-list it; that's a one-commit change on my side, no argument.

Either way, bug reports that arrive through FlatPark get triaged by me first, and only reach you if they reproduce with the plain portable tarball outside Flatpak.
