### ISSUE TITLE
Lagging persists in 1.8-RC as well.

### ISSUE THREAD

**Issue by Incantatoric** [DeaDBeeF-Player/deadbeef#2107]
### Steps to reproduce the problem
Just start playing any song.
Play any song, pause it and then resume it.
Wait until a song is finished and then switch to the next song.

### What's going on? Describe the problem in as much detail as possible.
There's a brief lagging - about 2-3 seconds - before it plays the new song, resumes or plays the next song.
In the previous report the problem was solved by using 1.8-RC, but suddenly the problem is reproduced even in the recent version. 
The only thing happened in between is a reboot. Maybe I just have to wait for the next official update?

### Information about the software:

Deadbeef version: 0.7.2, 1.8-RC
OS: Arch Linux, KDE

**Comment by Alexey-Yakovenko** [comment]
For reference: previous issue: #2106

**Comment by Alexey-Yakovenko** [comment]
My local testing doesn't show the problem as described.
I'm testing in Ubuntu 14.04 in virtual box on a retina iMac 2017, where virtualbox is **incredibly** slow and laggy because of some graphics incompatibility, still I'm not experiencing any issues with the sound output between songs or after pausing / resuming.
I'm trying to get testers to report whether this is happening on their machines.

**Comment by Alexey-Yakovenko** [comment]
Also since no bugs like this have been reported since the 0.7.2 original release, and many people including myself have used deadbeef on a daily basis all this time -- I tend to believe you might have some local misconfiguration issue.

I'm not the best linux troubleshooter out there.. but let's see what you may try.

Create a new clean user account, then run a freshly downloaded deadbeef copy in it.. see if the issue persists.

If the problem persists, try logging into another DE, or even better an empty X session where you just have an xterm window. It's important to do this with the same fresh user account without any customizations. See if the problem still persists.

If this doesn't solve the issue, you might have something in your system-wide settings. Try to remember whether you modified any of the ALSA or PulseAudio system configuration files, or did any other system tweaks which may affect sound performance.

Of course there's a possibility that the newer ALSA or pulseaudio or linux kernel have affected deadbeef sound playback in some new unknown way, and the only way to know for sure is to install and run new arch linux on my machine. I'm gonna try that, but I'm way too old and lazy for this kind of stuff, and if it takes too long -- I'll probably give up.

**Comment by tomjepp** [comment]
I use deadbeef very frequently on Arch + KDE Plasma 5, and I don't see this.

Setup for me is a i7 4770K CPU, 32G of RAM and playback is via a USB DAC. Music is stored on a NFS server (so not particularly quick to access).

**Comment by kpcee** [comment]
Here under Antergos (Arch Linux) with Xfce I cannot reproduce the described problem.

**Comment by Alexey-Yakovenko** [comment]
I couldn't figure out how to install archlinux, but we got two votes that the bug doesn't occur on other archlinux installations.
