### ISSUE TITLE
Loading PLS playlist with relative paths causes error logging

### ISSUE THREAD

**Issue by oyvindstegard** [DeaDBeeF-Player/deadbeef#2125]
### Steps to reproduce the problem

Load a PLS playlist having relative paths, like `File1=../some/file.flac`.

### What's going on? Describe the problem in as much detail as possible.

Loading PLS playlists containing relative audio file paths gives one `ERROR: could not load: <path>` log event per file in playlist, but it still loads OK and all files play. So might just be case of wrong logging, but still annoying, since it pops up a window with the errors everytime I load a playlist.

I use the Ubuntu snap package, but the same error also happens with the static portable build. The same playlist files load fine in Deadbeef 0.7.2.

### Information about the software:

Deadbeef version: 1.8.0 (snap package)
OS: Ubuntu 18.04

**Comment by Alexey-Yakovenko** [comment]
It's likely that 0.7.2 had this error as well, just printing it to the console. I'll check it out.

**Comment by Alexey-Yakovenko** [comment]
@oyvindstegard 

The previous fix to this issue has been reverted, since it caused certain network streams to be mis-detected as relative local paths.

However, even after reverting, I can't reproduce this issue anymore.

Would be great if you try to reproduce it again, and if it's still a problem -- I could attempt a different fix.
