### ISSUE TITLE
Persistent log window on every launch

### ISSUE THREAD

**Issue by AcarBurak** [DeaDBeeF-Player/deadbeef#2193]
### Steps to reproduce the problem
Launch deadbeef (every time)
### What's going on? Describe the problem in as much detail as possible.
As I don't have gtk2 installed (not needed), log window appears saying:
```
plugin converter_gtk2.so not found or failed to load
plugin pltbrowser_gtk2.so not found or failed to load
plugin shellexecui_gtk2.so not found or failed to load
plugin vfs_zip.so not found or failed to load
```
### Information about the software:
Terminal outputs this:
```
found gui plugin ddb_gui_GTK2.so
added GTK2 gui plugin
found gui plugin ddb_gui_GTK3.so
added GTK3 gui plugin
load gui plugin
checking GUI plugin: GTK2
checking GUI plugin: GTK3
found selected GUI plugin: GTK3
...
loading plugin /usr/lib/deadbeef/converter_gtk2.so
dlopen error: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
trying /usr/lib/deadbeef/converter_gtk2.fallback.so...
plugin converter_gtk2.so not found or failed to load
...
loading plugin /usr/lib/deadbeef/pltbrowser_gtk2.so
dlopen error: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
trying /usr/lib/deadbeef/pltbrowser_gtk2.fallback.so...
plugin pltbrowser_gtk2.so not found or failed to load
...
loading plugin /usr/lib/deadbeef/shellexecui_gtk2.so
dlopen error: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
trying /usr/lib/deadbeef/shellexecui_gtk2.fallback.so...
plugin shellexecui_gtk2.so not found or failed to load
...
dlopen error: libzip.so.5: cannot open shared object file: No such file or directory
trying /usr/lib/deadbeef/vfs_zip.fallback.so...
plugin vfs_zip.so not found or failed to load
```
Deadbeef version: 1.8.2
OS: Arch

**Comment by saivert** [comment]
If you don't have GTK2 libraries installed it is expected that you also then don't have the deadbeef GTK2 UI plugins installed.
I see that the Arch Linux package has both GTK2 and GTK3 as optional dependencies so this is a problem. I would think simply having two packages deadbeef-gtk2 and deadbeef-gtk3 would be better in this case. [This is the case](https://www.archlinux.org/packages/?sort=&q=-gtk2&maintainer=&flagged=) for other packages in the Arch repositories

As for the UX improvements I would suggest to add the plugin to the blacklist so it only shows the error once. Ideally this would be used to improve the plugin list in the preferences and finish the implementation of the enable/disable checkboxes for each plugin.

**Comment by unclebrr** [comment]
OK. All nice with plugins and libraries, but why log window shows up every time it sees not music file in the directory where it's been opened???
For example: I have 10 music files and info.txt file in the same dir, I'm loading the whole dir for playing and I get "failed to add file or folder ~/dir1/info.txt" And it happens every time I'm loading any directory! Could it be switched off somehow? If I need a log I can check it in the menu.

**Comment by Alexey-Yakovenko** [comment]
Do you add a directory, or all files in the directory? It's two different scenarios, and if you add all files -- unsupported files would produce an error. Right now it's not possible to suppress error messages. They are there to inform the users about problems.

**Comment by unclebrr** [comment]
Whole directory. Just upgraded from 0.7.1 to 1.8.2 - there was no such problem in 0.7.1. Been amused ;)

**Comment by Alexey-Yakovenko** [comment]
Yeah, 0.7.x didn't have the error log window -- which is a problem of its own.
It looks like your issue is a different problem, than what this issue is about. You should probably post a new bug report with precise repro steps. This way you would increase a chance of someone noticing it, and if they have a clear understanding what's going on -- it would be easy enough to work on a fix.

**Comment by unclebrr** [comment]
Done.

**Comment by p3732** [comment]
So I am not sure what to take away from this issue.

I had the same problem as the OP with the Arch version, which has libzip, the dependency of the vfs_zip plugin, as an optdep. This led to the log output window to pop up on every start, which does make sense. But if I understand correctly, then the vfs_zip plugin is optional. However it causes errors when not being able to load. I as user don't see an easy way to disable the plugin with the UI. 

So is it simply packaged in the wrong way, as in libzip is a hard dependency if deadbeef is build with vfs_zip plugin support? Or should the plugin just be silently disabled if libzip is not present?

I am asking because I wonder if it is a downstream plugin or a general issue of deadbeef.

**Comment by Alexey-Yakovenko** [comment]
It's a chicken-egg problem. On one hand some users want to know when plugins fail to load because their dependencies are missing. On another hand, this mechanism was historically used to have plugins intentionally disabled, by not installing their dependencies (like libzip). I don't know how to solve this yet. Not because there's no solution, but simply because I didn't have time to work on this yet.

**Comment by p3732** [comment]
Ah, okay, thank you for clarifying.

I would say the log is definitely a step in the right direction to solve this for power-users, but I believe defaulting to not showing the log would be the more non-technical-user-oriented approach. Maybe the disabled plugins can also be listed in the preference dialog with an explanation of why they are disabled. That probably is easier to achieve than having some mechanism of enabling and disabling plugins, which comes with its own set of problems entirely.

**Comment by Alexey-Yakovenko** [comment]
I think the solution should be to log plugin dlopen errors at lower priority, which won't cause log window to popup. I don't remember what's the state of log UI right now though, and this might take some more work.
Listing disabled/failed plugins in a specialized dialog is kinda useless IMO, as it wouldn't add any new information compared to the log, but would add a lot of coding work.

**Comment by p3732** [comment]
Priority logging sounds like a good solution, yes.

What I meant with the other suggestions was listing disabled plugins with all the other plugins, so that when a user wonders why the plugin is not working, then the reason can also be found there. But yes, the log should be a sufficient way, especially if that would cause too much code effort.

**Comment by erm3nda** [comment]
I would add just an opt-out of the registry dialog. I will be warned once, and being aware of it voluntarily disable the dialog with that opt-out.

Doesn't break the program, and let's the user to choose if he want to be warned again.

Options -> Show Registry dialog on startup.
