### ISSUE TITLE
plugin vfs_zip.so and plugin cdda.so not found or failed to load

### ISSUE THREAD

**Issue by randomkit** [DeaDBeeF-Player/deadbeef#2202]
### Steps to reproduce the problem
start deadbeef

### What's going on? Describe the problem in as much detail as possible.
when start deadbeef i get journal message:
"plugin cdda.so not found or failed to load
plugin vfs_zip.so not found or failed to load"

### Information about the software:

Deadbeef version: 1.8.2
OS: Arch linux
 start log in attach file (or must i put it in comment?)

[deadbeef_start.log](https://github.com/DeaDBeeF-Player/deadbeef/files/3558745/deadbeef_start.log)

**Comment by Alexey-Yakovenko** [comment]
It's quite obvious what you need to do, if you look at the deadbeef_start.log yourself.

**Comment by cubetronic** [comment]
woooow... "rtfm"

**Comment by Alexey-Yakovenko** [comment]
Well it's not an issue with deadbeef, but rather with how arch package is built, and how the optional dependencies are shown to the users.
In short, you need to install what is not installed, and then it will work.

**Comment by tullo-x86** [comment]
@randomkit @cubetronic The clue is in the logfile:

```
loading plugin /usr/lib/deadbeef/cdda.so
dlopen error: libcdio.so.19 (...some Cyrillic that I can't read...)
```

For this, you need the library `cdda.so` from your distribution. On Arch, the package you need to install is `libcdio` from the `extra` repository.

The other failure requires `libzip.so`, which on Arch is in `extra/libzip`.

In this developer's opinion, if these are _truly_ optional dependencies, DeaDBeeF shouldn't be displaying errors on startup. If they _are not_ optional, someone needs to contact Lukas Fleischer who maintains the Arch package, and have him update the package to list those libraries as hard dependencies instead of optional dependencies.

**Comment by Alexey-Yakovenko** [comment]
The plugins are optional and can be removed.
If the plugins are present, they are attempted to be loaded, and fail because their dependencies are missing.
This is important error information, and should not be omitted.
I suggest to change arch package and make all dependencies of the plugins non-optional.

**Comment by tullo-x86** [comment]
So if I understand correctly, the error occurs because of these three conditions:

* The plugins are all included in the Arch package
* The plugins reference shared objects which aren't flagged as hard dependencies in the Arch package
* All included plugins are always loaded at startup

My question is this: based on the application architecture of DeaDBeeF, is this actually a packaging problem? Would it be more "correct" for the plugins (e.g. `deadbeef-plugin-cdda`) to be packaged separately (as optional dependencies of a main `deadbeef-base` package), which each have their own hard dependencies (e.g. `libcdio`)? The maintainer could then create a metapackage to replace the existing `deadbeef` package, which depends on `deadbeef-base` and all its plugins, so that existing installs don't break.

**Comment by Alexey-Yakovenko** [comment]
Yes, I guess this would solve the problem.

**Comment by tullo-x86** [comment]
Should I interpret your answer as "yes, this package structure makes sense for the architecture of this application, and is unlikely to cause problems in the future"?

**Comment by Alexey-Yakovenko** [comment]
It's not something I can control or predict. It's up to the package maintainers to decide what is best for them and their users. Architecture didn't change, it was this way since the beginning.

**Comment by panchoporteno** [comment]
Arch's principles are KISS... loading a music-player and having to think to read the log file when opening it defeats this... it should just work..
tullo-x86 - you're amazing.. 
Alexey - was there any oxygen in the box you just got packed into..

**Comment by Alexey-Yakovenko** [comment]
@panchoporteno 

I'm not in charge of arch packages, and I'm not making an application for ArchLinux -- it's multiplatform, and distro-independent.

The player displays actual errors. If there are no errors -- the log is not displayed.

There's a number of ways to fix the errors -- delete the plugins which can't load, or install dependencies to make them work, and possibly contact the package maintainer to change the packaging to satisfy the dependencies correctly.

You can also use one of the official builds, which won't have the issues, and won't display the errors.

These errors were always there, now they are also displayed in the UI, and simplify problem diagnostics and bug reporting.

**Comment by tullo-x86** [comment]
@Alexey-Yakovenko It sounds like you agree that my suggestion to change the packages is the "most correct" way to fix this issue. I will recommend it to the Arch package maintainer.

The reason I asked for confirmation about appropriateness for DeaDBeeF's architecture is because the "obvious" solution to a problem is not automatically the best one. I am an outsider from the Internet — I don't know what is planned for your project's future.

I appreciate the feedback anyway. Thank you for your continuing work on DeaDBeeF.
