### ISSUE TITLE
The elapsed time in replaygain scanner isn't correct.

### ISSUE THREAD

**Issue by laichiaheng** [DeaDBeeF-Player/deadbeef#2217]
### Steps to reproduce the problem
Scan replaygain
### What's going on? Describe the problem in as much detail as possible.
The elapsed time is much much longer than real elapsed time.
It has only passed for 1 to 2 hours.
![2019-09-16 15-55-53 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/64941961-7f129c00-d89a-11e9-8536-6e78f3579d19.png)

### Information about the software:

Deadbeef version: deadbeef-git
OS: Manjaro

**Comment by Alexey-Yakovenko** [comment]
I can't reproduce this. At least not on shorter periods of time (up to 1 minute). Elapsed time is reported correctly on both mac and linux.

In which case, the issue might be caused by some precision loss on larger numbers, and needs to be investigated further.

Can you verify whether you observe the same on your machine?

**Comment by kpcee** [comment]
I can reproduce the problem, but only happens with a larger number of files. In this case both timers do not output optimal values.
![pic](https://user-images.githubusercontent.com/39984895/70982759-7905a480-20af-11ea-89c3-61909c853025.png)
