### ISSUE TITLE
Edge cases with GUI plugins (not really a bug)

### ISSUE THREAD

**Issue by eblanca** [DeaDBeeF-Player/deadbeef#2258]
### Steps to reproduce the problem
I've built deadbeef on a shiny new system with no development headers for GTK2/GTK3, just a bunch of codecs available.

### What's going on? Describe the problem in as much detail as possible.
Build process reaches the end, deadbeef gets installed and runs.
The issue is, nothing else happens because no GUI plugin exists, so no window, no menu and no interaction with deadbeef.
Even closing/quitting the application becomes impossible, so I hit CTRL+C as a last resort.

### Information about the software:
Deadbeef version:
git master branch commit 15823ac726214fccbc8e1d3b1750abbd5c24e3b7
OS: LMDE x64 (Debian based)

I think it's quite weird the build process exits normally, as with no GUI plugin deadbeef cannot be used at all. Maybe the build should not even start when no GUI plugins can be built ?
On the other hand, when deadbeef is correctly installed but is does not find any GUI plugins at startup (removed by mistake?), then it should not start at all, should it ?

**Comment by Alexey-Yakovenko** [comment]
All of this is fine, and by design.

It can play audio, it can be controlled via command line, it can also load an alternative UI plugin which is not part of deadbeef build system itself.

There are many use cases for that.
Deadbeef is not a monolithic application, it's basically a plugin launcher.
UI is just one of the plugins.
