### ISSUE TITLE
Album Art Blurry On HiDPI Displays (linux)

### ISSUE THREAD

**Issue by RelentleSausage** [DeaDBeeF-Player/deadbeef#2382]
### Steps to reproduce the problem
Play a track and look at the album art in the album art viewer.
### What's going on? Describe the problem in as much detail as possible.
Album art I know is hi res enough looks sort of blurry or low res on a HiDPI display (4k). It kinda looks like a LoDPI album art scaled up to 4k. I've tried DeaDBeeF on various distros (fedora, opensuse, arch, kubuntu, pop os, ubuntu) and this problem was there on all of them. I've tried many formats (DSD, flac, mp3, ogg, wav) to see if that made a difference and it did not. I'll attach a photo of how it looks. I'll use album art where the lines should not look blurry at all but they should look extremely sharp and well defined. It's 3000x3000 album art so I know that's not the issue. It may not look too bad in the screenshot because it is much smaller on the screen than in deadbeef (it's taking up half of DeaDBeeF).
![Screenshot_20200509_173114](https://user-images.githubusercontent.com/50790188/81488265-61c08280-921b-11ea-8057-a9c3e8752c34.png)

### Information about the software:
Deadbeef version: 1.8.3
OS: Fedora 31 KDE edition

By the way, great work on DeaDBeeF. It's one of the first truly great linux music players I've found. Love all the features for audiophiles :). 

Thanks in advance!

**Comment by Alexey-Yakovenko** [comment]
I'm quite sure that deadbeef downsizes album art to some fixed max size.

This is quite necessary, since a single image like this is 36MB in RAM (probably way more, depending how cairo and X11 are handling those), and deadbeef has in-RAM cache for 20 images or something like that, so you'd get 1GB of RAM wasted - which is not acceptable for most users, even if they use album art.

The album art support in deadbeef is designed to handle fast loading and displaying small "thumbnail-size" images, with low memory footprint, but it can't handle hi-res images at all.

**Comment by RelentleSausage** [comment]
Hey, so I know that I posted this years ago but I've recently reinstalled the current version of DeaDBeeF on MacOS and this issue is remedied by adjusting the image size slider in preferences -> plugins -> album artwork. I don't have a linux machine currently but if this feature is also available in linux then I would consider this issue fixed.
