### ISSUE TITLE
Albums with a large number of tracks are not sorted numerically (with custom sort)

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [DeaDBeeF-Player/deadbeef#2429]
### Steps to reproduce the problem
1. Have at least one album with over around 120 tracks
1. Sort with `%album artist% - %year% - %album% - %discnumber% - %tracknumber%`
1. Note that 12 is between 119 and 120

### What's going on? Describe the problem in as much detail as possible.

I would expect that entries are numerically sorted, it appears they are logically sorted, or, when the tracknumber gets high this happens. Items are correctly sorted when *only* using track numbers.

![Screenshot from 2020-08-11 18-24-18](https://user-images.githubusercontent.com/21071450/89922862-f0b8ae80-dbff-11ea-90e8-da8ad04be27a.png)

### Information about the software:

Deadbeef version: 1.8.3
OS: Ubuntu 20.04, kernel 5.8.0

**Comment by Alexey-Yakovenko** [comment]
This will sort alphabetically by string, the algorithm won't be recognizing numbers, and as a string, 12>119.
It works with 1 digit numbers, since `%tracknumber%` pads them with 0 automatically.

To solve this you need to use `%track number%` instead (it doesn't add zeroes by itself), and then pad with zeroes using `$num`, like this: `$num(%track number%,4)`

**Comment by A-UNDERSCORE-D** [comment]
That works perfectly, thanks!
