### ISSUE TITLE
Mono 22 kHz MP3 files play at double speed

### ISSUE THREAD

**Issue by glowinthedark** [DeaDBeeF-Player/deadbeef#2439]
### Steps to reproduce the problem
Play the file from http://www.namoamitabha.net/namo_mp3/amitabha/amitabha_path2west.mp3

### What's going on? Describe the problem in as much detail as possible.
File plays at double speed

### Information about the software:

Deadbeef version: Version 1.0 (1)
OS: MacOS 10.15.6 (19G2021) 2.4 GHz 8-Core Intel Core i9, 32 GB 2667 MHz DDR4, AMD Radeon Pro 5300M 4 GB
Intel UHD Graphics 630 1536 MB

### NOTES:
Also happens with 16kbps 8kHz files (see attached zip file)

[03-chant-03.mp3.zip](https://github.com/DeaDBeeF-Player/deadbeef/files/5156180/03-chant-03.mp3.zip)

**Comment by Alexey-Yakovenko** [comment]
The provided 8KHz file plays identically to Finder preview here, the speed seems right.
Also tested 22KHz mp3, plays correctly.
I'm not denying that on your computer this problem is happening, but I can't fix this without a way of reproducing it.
I tested on 3 different computers - 2020 macbook air, 2017 iMac and 2019 macbook pro, all running slightly different OS versions, Catalina and Big Sur.

**Comment by Alexey-Yakovenko** [comment]
Is it possible that you're running an outdated version of deadbeef? The mac version doesn't have an official stable release, but the CI build is updated multiple times per week. Try to redownload. https://sourceforge.net/projects/deadbeef/files/travis/osx/master/deadbeef-devel-osx-x86_64.zip/download

**Comment by glowinthedark** [comment]
@Alexey-Yakovenko: also reproducible with the version you linked.

**Comment by Alexey-Yakovenko** [comment]
By any chance, did you change any settings? Perhaps deleted the resampler plugin from DSP chain settings? Or changed its parameters?

**Comment by Alexey-Yakovenko** [comment]
Typically, needs to look like this:

![image](https://user-images.githubusercontent.com/1895698/92312573-4d6e7580-efc2-11ea-94a7-6416bd12c0c5.png)
![image](https://user-images.githubusercontent.com/1895698/92312575-5101fc80-efc2-11ea-89e7-f9cee690a1de.png)

**Comment by glowinthedark** [comment]
@Alexey-Yakovenko: Under DSP I had no presets listed — this was OOTB; I did not change anything in the default configs. I added the resample and mono-to-stereo presets and now playback works as expected. Thank you!

I would still say this is a bug in the sense of the default OOTB configuration, since in an OOTB installation users have absolutely no way to discover that these DSP plugins must be enabled in order to play files with sample rates other than 44kHz.

> Sidenote: it would be helpful to be able generate all the debug info which would show all the configurations/versions for the app and plugins.

**Comment by Alexey-Yakovenko** [comment]
In a way you're right, that once you change that part of configuration -- there's no way to restore the defaults through the UI.
On the other hand -- if you did it by accident, you wouldn't know that you need to reset THIS part of the settings.

And.. it actually does work OOTB -- 2 of the 3 computers on which I was verifying this bug report didn't have deadbeef installed on them before.

The root of the problem is customizability. It's a strength, but also a weakness. You can customize some stuff without understanding, or by accident, and it will cause issues. If I make it non-customizable -- people will start asking for customization.
