### ISSUE TITLE
Feature request: "Restart or Previous" playback action

### ISSUE THREAD

**Issue by ToadKing** [DeaDBeeF-Player/deadbeef#2503]
Lots of audio players have a specific action when you do a "Previous" navigation option: If the current playing song has passed a certain time (usually only a couple of seconds) it will instead seek to the beginning of the song instead of going to the previous song. This allows for easy repeating of a playing song with one action while still allowing for navigating through playlists.

**Comment by saivert** [comment]
Could this be implemented without making yet another toggle in the preferences? Isn't this behavior expected, though I'm sure some users are used to the current behavior (always the risk of bugs becoming features, or this breaks someones workflow, see relevant XKCD).

**Comment by ToadKing** [comment]
My idea was to have a new action that a user can bind stuff to, so things like buttons in the program can use the old behavior and stuff like hotkeys can use the new one.

**Comment by ToadKing** [comment]
@saivert's PR add the feature to the hotkeys plugin, but I'm currently using the MPRIS2 plugin to handle media keys so it's not handled there. My idea was for the behavior to exist in a new message alongside `DB_EV_PREV` and `DB_EV_SEEK` that handles the logic, so each different plugin doesn't have to recreate the logic and potentially do it in different ways.

I'll try to make a PR with my idea later.

**Comment by Alexey-Yakovenko** [comment]
@ToadKing this feature doesn't require adding a new "system event" to deadbeef.
IMO it's fine to hardcode this behavior in MPRIS plugin by default.
This is what people expect when they use it, just like toggle play/pause by default.

**Comment by Alexey-Yakovenko** [comment]
The main reason why I don't like adding new events like this, is mainly because this would require bumping the required api version of the plugins, and reducing compatibility. Many people are still using 0.7.2, because 1.8 series have certain issues for some people, which will take time to resolve. This would be a significant inconvenience for them.

**Comment by saivert** [comment]
My wish was for actions in deadbeef to be more general and not just tied to the hotkeys plugin. Basically like GAction in modern GTK applications where you can define actions that can be triggered from everywhere really.

Currently plugins can invoke any defined action by enumerating all plugins, calling its `get_actions` function and then enumerating all actions find a matching action name, then invoke its `callback2` function. I do this in my headerbar plugin so I don't have to reimplement stuff that already has actions. It means that my plugin requires the presence of the hotkeys plugin as it defines a lot of standard actions.

**Comment by Alexey-Yakovenko** [comment]
It's entirely possible for the MPRIS plugin to call the action from hotkeys plugin.
They work kind of similar to GActions.
That's how GTKUI plugin access them for hotkeys.

**Comment by Alexey-Yakovenko** [comment]
I see that we understand everything the same way, and have similar goals.
It sounds like you want the same thing as the plugin actions provide, but you want to have some higher level API to them.

**Comment by Alexey-Yakovenko** [comment]
> It means that my plugin requires the presence of the hotkeys plugin as it defines a lot of standard actions.

This is correct, and this is intentional.
This is necessary for a number of reasons:

1. Sharing action code across different UI plugins / platforms (linux+gtkui, mac+cocoa, ...)
2. Allowing plugins to create new actions (shellexec, GTKUI, lastfm, ...)

I understand, that perhaps the hotkeys is not the best vessel for the generic cross-platform actions, but at the time the code was created -- there was nothing that worked better.
I suppose, this code is technically possible to move into the main application binary, and expose through some kind of dummy "core" plugin.
