### ISSUE TITLE
Playing a folder with .cue prioritizes all the audio Tags

### ISSUE THREAD

**Issue by rootsandculture** [DeaDBeeF-Player/deadbeef#2629]
If I drag a folder to the playlist containing a .cue file and separate FLAC files makes the tags from the files changes, and in the selection propierties appears info from the .cue file than isn't present in each FLAC file tags. It's really annoying, cause cannot fix the tags with proper one (i.e. all lowercase). Seems the .cue info in the folder replaces all the info displayed.

![Screenshot from 2021-07-06 12-12-38](https://user-images.githubusercontent.com/71974607/124626192-d52c4700-de54-11eb-933b-4d642a32b96f.png)

![Screenshot from 2021-07-06 12-12-29](https://user-images.githubusercontent.com/71974607/124626186-d3fb1a00-de54-11eb-992a-fbbc80f48810.png)

Deadbeef version: 1.8.7
OS: Fedora 34

**Comment by Alexey-Yakovenko** [comment]
This is the intended behavior. If you need to add a file without CUE, for example for editing tags -- you need to add it to the playlist individually, without the folder or the accompanying cue file.

**Comment by rootsandculture** [comment]
But if I add it individually and make the proper tags editing, when add the folder again the .cue bypasses all the changes.

**Comment by Alexey-Yakovenko** [comment]
Yes, as a general rule in deadbeef, external files (metadata, album art) take precedence over the internal / embedded metadata. If the cuesheet contains the same fields as the embedded tags -- the cuesheet fields are assumed to be more true, and are getting used.

You can't exclude the cuesheets when drag-dropping the whole folders -- you can only exclude cuesheets by dragging the individual files.

**Comment by Alexey-Yakovenko** [comment]
> I'm constantly filtering and dragging my library from nautilus cause I didn't find another procedure or plugin for managing the entire library.

The media library manager is under development, but it has the same behavior. Even more strict -- the library scanner always loads cuesheets, and they can't be excluded.

Although in the long run, I think there will be an option to disable cuesheet loading, but I'm not sure whether it would help your particular case, since it seems you need to pick whether to use cuesheet or not *per folder*. This can potentially be implemented by adding some extra metadata files, such as ".deadbeef-ignorecue" to tell the scanner that cuesheets need to be ignored for this specific folder.
