### ISSUE TITLE
Progress bar cannot be customized into spectrum in MacOS

### ISSUE THREAD

**Issue by marcustone** [DeaDBeeF-Player/deadbeef#2632]
### What's going on? Describe the problem in as much detail as possible.
Progress bar cannot be customized into spectrum in MacOS
![Snipaste_2021-07-09_23-17-01](https://user-images.githubusercontent.com/17929904/125103300-cb356d00-e10e-11eb-80c2-753adc2dd081.png)

### Information about the software:
No plugin available on Mac currently to transform progress bar into such beautiful spectrum?
The raw design does not look good and not user friendly
![Snipaste_2021-07-09_23-39-35](https://user-images.githubusercontent.com/17929904/125103446-ef914980-e10e-11eb-8465-75b43219753f.png)

Deadbeef version:Version 1.0 (bbe2f0a)
OS:Mojave

**Comment by Alexey-Yakovenko** [comment]
This is not a valid issue. Deadbeef on mac doesn't yet support customization, and while it's something that is being worked on -- it will take some time until it gets to the comparable customization features with the GTK version.

**Comment by marcustone** [comment]
> This is not a valid issue. Deadbeef on mac doesn't yet support customization, and while it's something that is being worked on -- it will take some time until it gets to the comparable customization features with the GTK version.

Is there an expected release schedule Alexey? Like in late 2021 or early 2022?

**Comment by Alexey-Yakovenko** [comment]
It's a non-commercial hobby project. Creating release schedules is not really possible, we can't predict how much time we can work on the project, and which features will be worked on at which point in time.
I can only describe the current state of theUI customization feature you asked about, and try to predict **how** it will come out when it's "done". But not **when**.

There are 3 features that are being worked on "at the same time" on the medialib branch:

* Media library -- scanner, sidebar, search, UI and related things.
* Arwork -- the "new" artwork plugin, which handles loading album art. Mainly because it's required to make the Media Library look nice and smooth, and because we need it to work well to be able to use it on both mac and linux. Currently it's only used on mac.
* UI Customization for Mac -- not really related to medialib that much, but it's the branch that I'm working on long term, so it was convenient

The idea is that all 3 areas will be complete and "released" at the same time, on mac and linux.

UI Customization on mac is slightly different than on linux, especially because of how Sidebar and Toolbar work and how they are integrated with the window on mac.
The standard Toolbar, Sidebar and Statusbar will not be customizable, but the central area will be fully customizable.
The idea is that if the user wants to have something else than the normal mac Toolbar -- they would have to hide the toolbar, and create a custom one using the customization features.

The initial plan for UI customization on mac is to provide the means for plugin developers to make the UI extensions, and to have some basic elements -- playlist, spectrum analyzer, album art viewer.
Other elements -- such as custom seekbars -- will come later, when the respective developers will make the plugins work on mac.

There's no timeline for any of this though.
