### ISSUE TITLE
A single cover art image does not show with deadbeef

### ISSUE THREAD

**Issue by orbea** [DeaDBeeF-Player/deadbeef#2667]
### Steps to reproduce the problem

1. Download this [cover art](https://github.com/DeaDBeeF-Player/deadbeef/files/7111816/cover.jpg.txt) jpg and remove the `.txt` extension.
2. Add it somewhere so that deadbeef tries to use it.
3. The cover art is not recognized.

### What's going on? Describe the problem in as much detail as possible.

A single specific `cover.jpg` file never loads with deadbeef and remains blank. Most if not all other cover images I have do work, I'm not sure why this one is special? It does open correctly with `feh(1)`, but `viewnior(1)` also fails to open it. Maybe this issue more general than deadbeef?

file(1) says:
```
cover.jpg: JPEG image data, JFIF standard 1.01, resolution (DPI), density 72x72, segment length 16, baseline, precision 8, 500x500, components 3
```

### Information about the software:

Deadbeef version: https://github.com/DeaDBeeF-Player/deadbeef/commit/4744b3a205a3389eb0033ce57fe4b27c7b53abec
OS: `Slackware64`

**Comment by JakeSFR** [comment]
Yes, it seems to be a more general issue. Your 'cover.jpg' opens just fine for me in feh, Viewnior and DeaDBeeF itself:

![db_cover_jpg](https://user-images.githubusercontent.com/6226504/132134198-c3113b34-6615-4529-aead-2e93b22a2db2.png)

My hypothesis is that there could be something wrong with your gdk-pixbuf or `libpixbufloader-jpeg.so` specifically, because if I delete it in my OS (Fatdog64, gdk-pixbuf-2.36.12), then the 'cover.jpg' doesn't show up anymore in Viewnior nor DB, but it still does in feh (because it's using Imlib2 instead of gdk-pixbuf).

**Comment by orbea** [comment]
Thanks for testing, your hypothesis sounds plausible. I had `gdk-pixbuf-2.40.0` and now upgraded to `2.42.6` which is not any better. Maybe there is a regression sometime after `2.36.12`?

**Comment by Alexey-Yakovenko** [comment]
To my best knowledge, deadbeef doesn't use gdk for loading album covers.
It uses either libjpeg or libimlib2, depending how deadbeef is compiled.

**Comment by Alexey-Yakovenko** [comment]
(although, maybe I forgot, and gdk does get involved at some point in the chain)

**Comment by orbea** [comment]
A dependency tracking tool on slackware (`sbbdep(1)`) shows both `gdk-pixbuf2` and `imlib`, if the problem was in `imlib` it would probably affect `feh` too which it doesn't. It does not show `libjpeg` so I assume that is not relevant in this case.

**Comment by JakeSFR** [comment]
> Maybe there is a regression sometime after `2.36.12`?

I just built and tested 2.40.0 and still no problems.

Anyway, I launched the latest Slackware64-XFCE live in QEmu and there's definitely something weird going on.
Both DB and Viewnior (I just copied them from my host OS) can't display this cover.jpg. Viewnior shows:

`Couldn't recognize the image file format for file "/root/cover.jpg"`

and this message comes from gdk-pixbuf:

```
# strings /usr/lib64/libgdk_pixbuf-2.0.so | grep 'recognize the image'
t recognize the image file format for file 
```

However, if you open and save that file in GIMP, it automagically becomes viewable by Viewnior and DB.
One of the differences is (in Thunar's Properties -> Image tab):

```
Image Type: Unknown vs. jpeg (JPEG)
Image Size: Unknown vs. 500x500 pixels
```

Maybe there's a lib, used by both DB and Viewnior, that has problems with these "unknowns"..?
Btw, the file itself seems to be produced by PhotoShop 3.0, at least that's what hexdump shows.

Also, there is no _/usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-jpeg.so_ in at all, so it's not the culprit; after all other jpegs work fine, so something else must be dealing with them.
It still might be _libgdk_pixbuf_ or one of its deps, though.

Anyway, I'm not really familiar with Slackware, so I'm afraid you need to dig deeper yourself.

**Comment by JakeSFR** [comment]
Since the stuff in your OS appears to be newer than in mine, I decided to get to the bottom of this issue, because the same might happen to me in the future.
And I was right...

Long story short, this commit in shared-mime-info is responsible for the problem:

https://github.com/freedesktop/xdg-shared-mime-info/commit/3b1a9313396de96776393347dabd2458634073bf

It introduced some **"application/x-apple-systemprofiler+xml"** MIME with this match:

`<match type="string" value="&lt;plist version=&quot;1.0&quot;" offset="0:256"/>`

and guess what's inside of your jpeg:

```
# grep -ab 'plist version' cover.jpg 
252:<plist version="1.0">
```

A quick workaround is to open **/usr/share/mime/packages/freedesktop.org.xml**, find that MIME from above, decrease its priority from 50 to 49 in this line:

`<magic priority="50">`

and update MIME database with:

`update-mime-database /usr/share/mime`

After that both Viewnior and DB should be able to recognize that jpeg.

**Comment by Alexey-Yakovenko** [comment]
Thanks for investigating @JakeSFR 
Doesn't seem like anything can / should be done on deadbeef side, closing.
