### ISSUE TITLE
Question - covers2 & Output unrecognized characters

### ISSUE THREAD

**Issue by 0pLuS0** [DeaDBeeF-Player/deadbeef#2818]
Hello,

I just compiled 1.9.1 in Linux and I noticed there is now instead of 

```~/.cache/deadbeef/covers```

I now have;

```~/.cache/deadbeef/covers2```

Can we please get this reverted back to ```covers```?

I don't understand why the directory had to change? I have a lot of backups so it would be nice if it can be changed back to the original name.

THANKS

P.S. Just thought I'd mention this, in the startup output after the ```logger_free``` list, I have a section that has an unrecognized characters box being displayed.

Here's a screen shot;

![deadbeef output](https://user-images.githubusercontent.com/36190223/173758629-a674c750-125b-4f14-a79b-b4f63b5b24b2.jpg)

**Comment by Alexey-Yakovenko** [comment]
> I don't understand why the directory had to change?

It changed because the development of the artwork plugin required changing the naming scheme and folder structure of the cache, which is incompatible with older versions of deadbeef.

This means, that the artwork plugin was bumped to version 2, and the folder had to be renamed to avoid conflicts between different versions.

There's no way and no reason to use the same folder path. The contents are different / incompatible.

> P.S. Just thought I'd mention this, in the startup output after the logger_free list, I have a section that has an unrecognized characters box being displayed.

This means that your font doesn't display heart emojis.
It's supposed to display 💛💙

**Comment by 0pLuS0** [comment]
Hi,

Ok on the covers2.

For fonts, I'm using ```Sans Regular``` hmm

THANKS

**Comment by 0pLuS0** [comment]
I see it's the same in the About Window. What's a common font that will display these emoji in Linux?

💛💙

DeaDBeeF - The Music Player
Copyright © 2009-2022  Alexey Yakovenko and contributors
https://deadbeef.sourceforge.io

THANKS

**Comment by 0pLuS0** [comment]
Hi @Oleksiy-Yakovenko 

I just thought of this today, and I forgot to mention some details last year.

I'm running Slackware 15.0, I have all the default fonts installed, so I'm not understanding, that this needs something special to make work?

I hope you see this post, and you can help me understand, what sort of fonts I need to use, to display these images?

THANKS
