### ISSUE TITLE
Embeded covers are not display in oga, ogg, mp3 vbr formats

### ISSUE THREAD

**Issue by Npa972** [DeaDBeeF-Player/deadbeef#2973]
### Steps to reproduce the problem
Embed covers with kid3
Add to DeadBeef (plugins covert art default setting)

### What's going on? Describe the problem in as much detail as possible.
Covers are not display (ok with audacious, rhythmbox, quodlibet) in some formats (oga, ogg, mp3 vbr)
But only some albums seems to be concerned. Others albums in the same formats do not have cover's problem.

### Information about the software:
deadbeef-devel
Deadbeef version:
OS: archlinux

**Comment by Oleksiy-Yakovenko** [comment]
I embedded a random image into a random mp3 with kid3, and I don't observe any problem, the cover is loaded.
Without any other information, this bug report is not actionable.
I can only suggest to try deleting/cleaning the cover cache, since it may contain the previous version of the cover or a marker that a file doesn't contain a cover.
The cache is located in ~/.cache/deadbeef or something like that.
