### ISSUE TITLE
 if I enable OSD notify plugin and change many songs rapidly, I get the screen full of notifications

### ISSUE THREAD

**Issue by niels0n** [DeaDBeeF-Player/deadbeef#2996]
### Steps to reproduce the problem

Enable the plugin. Make many notifications appear.

### What's going on? Describe the problem in as much detail as possible.

The problem is that if I enable to plugin and change many songs rapidly, I get the screen full of notifications.
I think that there should be only one notification at once, with the new overriding the old one. Would that be possible?

### Information about the software:

Deadbeef version: 1.9.5
OS: EndeavourOS

**Comment by Oleksiy-Yakovenko** [comment]
It seems like it's a regression caused by rev 3f95b5694794a9a1aa8a04e8e032c64090f8f143
It's a bit hard to trace why this behavior had been changed, but it may have to do with some KDE-specific workarounds, where KDE (starting from 5.23.5) doesn't show updated notifications, and instead wants to get a new one for every track.

I need to reconsider making this optional - not sure why I did it the way it is, since I knew about this problematic behavior in some situations. Thanks for bringing it up.

**Comment by Oleksiy-Yakovenko** [comment]
I applied a fix and tested under GNOME and XFCE.

It works as designed under XFCE, but under GNOME it was behaving quite randomly, and I tend to believe it's a bug in GNOME.

**Comment by ferdnyc** [comment]
@Oleksiy-Yakovenko 

(I know this was a while ago, but... I doubt the situation has changed any, on the GNOME end.)

Notifications (and possibly other things) on GNOME 3 will likely be erratic and buggy unless the application is properly registered as a [GApplication](https://docs.gtk.org/gio/class.Application.html), since _everything_ GNOME does with notifications is centered around ownership by registered instances of an application. The GNOME Shell notification system supports the FreeDesktop protocol enough to _display_ notifications from any source, but _management_ of them after that point can be a different story.

Unless I'm missing it (and if so, my apologies, and please disregard this comment), I don't see any GApplication integration in the deadbeef code.

Whether or not it's documented / known (though it probably is, to some extent), I wouldn't be at all surprised if there are issues managing already-posted notifications that aren't owned by registered GApplication instances. I'd be equally unsurprised if those issues go away when the program owns an instance of GApplication, has called `GApplication.set_id()` to identify itself, and is registered to the system (`GApplication.get_is_registered()` returns `true`).

On the plus side, one of the benefits of having notifications associated with a GApplication instance is that it's even possible to withdraw or update notifications that were initially posted by _**a previous instance**_ of the program. As long as they have stable, well-known IDs and were posted by a registered GApplication, all instances are equally considered owner of all of the app's notifications, and the notification lifecycle is independent of any particular instance.

**Comment by Oleksiy-Yakovenko** [comment]
@ferdnyc 
The code you're looking for is here:
https://github.com/DeaDBeeF-Player/deadbeef/blob/master/plugins/gtkui/gtkui.c#L1883

It always uses GApplication when available (GTK >= 3.10.0)

But I doubt everything is as simple as you say.

Deadbeef doesn't use any GNOME APIs for sending OSD notifications -- it uses a separate plugin, which sends directly via DBUS.

**Comment by ferdnyc** [comment]
> [@ferdnyc](https://github.com/ferdnyc)
> The code you're looking for is here:
> https://github.com/DeaDBeeF-Player/deadbeef/blob/master/plugins/gtkui/gtkui.c#L1883

You're absolutely right (I was only looking in `src/`, which in retrospect was stupid), which renders the rest of my comment invalid. As I said, please disregard. Sorry for the noise.
