### ISSUE TITLE
no visible tesxt in playlist full of songs

### ISSUE THREAD

**Issue by samael-1982** [DeaDBeeF-Player/deadbeef#3097]
### Steps to reproduce the problem
Standard installation of Ubuntu from downloadable media, deedbeef 1.9.6 from sourceforge.
### What's going on? Describe the problem in as much detail as possible.
After some auto updates deadbeef stopped to launch.
I've done 'sudo apt install libcanberra-gtk-module libcanberra-gtk3-module'
After that deadbeef starts to work - but nothing in Playlist. (here was full playlist of songs)
Then I uninstall these packages, but Playlist still empty.
![image](https://github.com/DeaDBeeF-Player/deadbeef/assets/88877761/560b6502-ab8a-488b-b3bf-a55f0af26c7b)

### Information about the software:
Deadbeef version: Deadbeef 1.9.5, 1.96
OS: Ubuntu 22.04 LTS
desktop env: gnome
gtks:
ii  libgtk-3-0:amd64           3.24.33-1ubuntu2.1        amd64        GTK graphical user interface library
ii  libgtk-3-bin               3.24.33-1ubuntu2.1        amd64        programs for the GTK graphical user interface library
ii  libgtk-3-common            3.24.33-1ubuntu2.1        all          common files for the GTK graphical user interface library
ii  libgtk-4-1:amd64           4.6.9+ds-0ubuntu0.22.04.2 amd64        GTK graphical user interface library
ii  libgtk-4-bin               4.6.9+ds-0ubuntu0.22.04.2 amd64        programs for the GTK graphical user interface library
ii  libgtk-4-common            4.6.9+ds-0ubuntu0.22.04.2 all          common files for the GTK graphical user interface library
ii  libgtk2.0-0:amd64          2.24.33-2ubuntu2          amd64        GTK graphical user interface library - old version
ii  libgtk2.0-bin              2.24.33-2ubuntu2          amd64        programs for the GTK graphical user interface library
ii  libgtk2.0-cil              2.12.40-3ubuntu1          amd64        CLI binding for the GTK+ toolkit 2.12
ii  libgtk2.0-common           2.24.33-2ubuntu2          all          common files for the GTK graphical user interface library
ii  libgtk3-perl               0.038-1                   all          Perl bindings for the GTK+ graphical user interface library

**Comment by Oleksiy-Yakovenko** [comment]
It looks like the playlist columns got the wrong size, or got deleted.
You could try resizing the columns to get them back to acceptable size,
or you could manually delete the "corrupt" configuration from the file `~/.config/deadbeef/config`.
In order to do that:
* Quit the player
* Make a backup copy of the file `~/.config/deadbeef/config` - just in case
* Edit the file in a text editor, e.g. `$ gedit ~/.config/deadbeef/config` in command line
* Find the lines which begin with `gtkui.columns.playlist` and `gtkui.columns.search`
* Delete those lines, save the file
* Start the player again -- it should restore to default column settings.

**Comment by Oleksiy-Yakovenko** [comment]
I will assume that my previous comment will help to resolve issue. Please let me know if the problem is unresolved.
