### ISSUE TITLE
"Copy" item in context menu

### ISSUE THREAD

**Issue by Oleksiy-Yakovenko** [DeaDBeeF-Player/deadbeef#395]
Original [issue 466](https://code.google.com/p/ddb/issues/detail?id=466) created by Alexey-Yakovenko on 2012-04-19T10:49:52.000Z:

Foobar has a context item &quot;Copy&quot;, which lets me copy the filename (in my
case is this &quot;Artist - Title.mp3&quot;) to the clipboard. I just have to paste
this at discogs (and remove the .mp3 part) to find interesting information
on tracks to complete my file's tags. I never use automated tagging.

**Comment by bcoolumbo1** [comment]
Can you please arrange the two copy items in context menu underneath each other?
I always select "copy" by mistake when I need to select "copy info" for discogs and then I paste the whole file path and extension and have to go back to do it again. Always! It's because foobar has just one (the right for me) visible copy item in context menu, the other one is in a sub menu for file operations. Thank you.

**Comment by Alexey-Yakovenko** [comment]
@bcoolumbo1 
Can you please create a new issue, and possibly add some more information about the problem?
